### ISSUE TITLE
Horizontal review request: Intersection Observer

### ISSUE THREAD

**Issue by LJWatson** [w3ctag/design-reviews#435] opened 2019-10-28 16:21 UTC
The WebApps WG is preparing to transition the [Intersection Observer](https://w3c.github.io/IntersectionObserver/
) specification to Candidate Recommendation (CR), and would welcome your review.

We would appreciate your review by 31st January 2020, sooner if you can manage it.

If you could acknowledge receipt of this request and confirm that you intend to review the Intersection Observer specification, that would be helpful. 
 
Please file any issues on the [Intersection Observer repository](https://github.com/w3c/IntersectionObserver/issues
), and cross-reference [issue #395](https://github.com/w3c/IntersectionObserver/issues/395
) on the same repo (where we're tracking reviews).

With thanks
Léonie on behalf of the WebApps chairs and team

**Comment by torgo** [comment] 2019-11-05 21:19
could this be a duplicate of #197 ?

**Comment by LJWatson** [comment] 2019-11-05 21:51
Possibly, yes. #197 was filed by WebPlat whereas this was filed by 
WebApps. Whether there have been sufficient changes to the spec in the 
intervening two years to warrant another review, I'm not sure. @szager 
can you advise?

**Comment by szager-chromium** [comment] 2019-11-05 22:04
@LJWatson No, I don't think another review is warranted. All the changes since #197 have been small-bore cleanups.

**Comment by LJWatson** [comment] 2019-11-05 22:46
Thanks szager

@torgo I'll close this issue and resume discussion on #197.

**Closed** 2019-11-05 22:47 UTC
Labels: Review type: later review, Venue: Web Apps WG
