### ISSUE TITLE
inert attribute

### ISSUE THREAD

**Issue by alice** [w3ctag/design-reviews#610] opened 2021-02-16 10:22 UTC
Wil sha TAG!

I'm requesting a TAG review of the `inert` attribute.

A node (in particular elements and text nodes) can be marked as inert. When a node is inert, then the user agent must act as if the node was absent for the purposes of targeting user interaction events, may ignore the node for the purposes of find-in-page, and may prevent the user from selecting text in that node. User agents should allow the user to override the restrictions on search and text selection, however.

The `inert` attribute is a boolean attribute that indicates, by its presence, that the element and all its shadow-including descendants is to be made inert.

  - Explainer: https://github.com/WICG/inert/blob/master/explainer.md
  - Specification URL: https://whatpr.org/html/4288/16fbe73...d4ed883/interaction.html#inert-subtrees
  - Tests: https://wpt.fyi/results/inert
  - Security and Privacy self-review: https://github.com/WICG/inert/blob/master/security-privacy.md
  - GitHub repo: https://github.com/WICG/inert/
  - Primary contacts (and their relationship to the specification):
      - Alice Boxhall (@alice), Google/Chromium
      - Brian Kardell (@bkardell), Igalia
  - Organization(s)/project(s) driving the specification: Google/Chromium
  - Key pieces of existing multi-stakeholder review or discussion of this specification: 
    - https://github.com/whatwg/html/pull/4288
    - https://github.com/mozilla/standards-positions/issues/174 
  - External status/issue trackers for this specification: https://www.chromestatus.com/feature/5703266176335872

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/) 
  - Relevant time constraints or deadlines: No deadline, but hoping to ship soon. (I didn't realise until I was filling out the intent to ship that I never actually requested a TAG review, to my surprise.)
  - The group where the work on this specification is currently being done: WICG, WHATWG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): WHATWG
  - Major unresolved issues with or opposition to this specification: 
    - https://github.com/whatwg/html/issues/5650
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @alice

**Comment by LeaVerou** [comment] 2021-02-16 11:30
Hi @alice! 👋🏼 

Looking at the explainer, I'm missing some examples of how this is supposed to be used. If it's used on `<body>`, wouldn't it make the entire subtree inert, *including the `<dialog>` itself*? There often is a natural container for all content that excludes dialogs, popups, etc, but not always, so libraries cannot depend on it, and would need to introduce their own wrapper element, which is fairly intrusive. I suppose this is why `<dialog>` in the spec isn't actually defined in terms of the `inert` attribute?

Given that `inert` is currently a boolean attribute, it doesn't look like there's a way to override it on descendant subtrees. However, a way to do so could be quite useful to address the many cases where the inert subtree(s) contain the blocking elements or vice versa. Another example that comes to mind is UI to edit parts of an HTML page in place (e.g. a social media profile), by appending form elements within the elements being edited. One wants the parts of the page that are being edited to be inert, but the editing controls inside them to be interactive.

**Comment by robdodson** [comment] 2021-02-17 23:08
Hey @LeaVerou, @alice and I were just chatting about this in a call as a similar question came up on the WICG repo:
https://github.com/WICG/inert/issues/165

A quick example of how we recommend folks use inert is:

```html
<body>
  <main inert></main>
  <div class="dialog"></div>
</body>
```

We did discuss the idea of letting subtree items "uninert" themselves but we were concerned that it might lead to unexpected behaviors like every third-party ad trying to uninert itself.

Having said that, I think we both recognize that it would be a pretty useful feature. I don't want to speak for Alice, but I'm pretty open to what the larger CSSWG thinks on this point. If folks generally think that the value of letting subtree items break out of the inert tree is useful (and the downsides aren't too great) then maybe we should rethink this bit.

**Comment by dylanb** [comment] 2021-02-18 15:07
@robdodson @alice the spec does not specify what happens to the focus when an element with the focus becomes `inert`. Should it?

**Comment by domenic** [comment] 2021-02-18 16:07
> @robdodson @alice the spec does not specify what happens to the focus when an element with the focus becomes inert. Should it?

This is actually already in the HTML spec, covered as a general case: https://html.spec.whatwg.org/#focus-fixup-rule

**Comment by torgo** [comment] 2021-02-22 17:58
[Discussed in breakout this week](https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/02-22-agenda.md) and it appears a privacy & security questionnaire response is still pending. We've bumped it 2 weeks and hope to have a response back when we revisit it then.

**Comment by alice** [comment] 2021-02-23 02:30
Thanks, the s&p questionnaire is now linked from the top comment.

To Lea's [question](https://github.com/w3ctag/design-reviews/issues/610#issuecomment-779776894), about whether this should have a mechanism for overriding inert in sub-trees:

I can't find any documentation, unfortunately, but I recall that @robdodson, @bkardell and I gave this quite a bit of thought and decided that, on balance, the inability to override was the right design.

This makes the API simple in two ways:

- Firstly, it means a straightforward boolean attribute can be used, instead of a string-based pseudo-boolean.
- Secondly, it means there's no need to define any kind of precedence or `!important` type rule to ensure that no content becomes "un-inert" when it's not supposed to. It makes it trivially easy to reason about: if something has an ancestor with `inert` set, it is inert.

Obviously, this does mean that authors who want to use this for modal UI need to keep the modal outside of the container which has `inert` on it. However, the popularity of the [polyfill](https://www.npmjs.com/package/wicg-inert) suggests that developers haven't found this to be an unreasonable burden.

There is some discussion on this topic on an [issue thread](https://github.com/WICG/inert/issues/69). In particular:

Maciej Stachowiak [wrote](https://github.com/WICG/inert/issues/69#issuecomment-489915986):

> the inability to escape `inert` from within a subtree seems like a feature not a bug

I [followed up](https://github.com/WICG/inert/issues/69#issuecomment-490276933):

> ... on my backlog of "ideas to write up as concrete proposals" is a top layer API which would explain both the "inert everything else" and the stacking behaviour of dialogs. I think those two things belong together, as the "inert everything else" behaviour is visually indicated by the combination of stacking and backdrop. It would obviously reuse the definition of "inert" used by both `<dialog>` and the `inert` attribute.

**Comment by alice** [comment] 2021-03-15 03:15
Little worried this has landed in the abyss :)

**Comment by LeaVerou** [comment] 2021-03-24 15:44
We discussed this in the Plenary today and we all agree we are happy with it. The reasoning behind subtrees being unable to un-inert themselves seems sound.
Therefore, we will close this. Thank you for filing it and please let us know if we can be of any more help.

**Closed** 2021-03-24 15:44 UTC
Labels: Resolution: satisfied, Topic: HTML, Venue: WICG
