### ISSUE TITLE
Add simpler reading methods to Blob interface.

### ISSUE THREAD

**Issue by jarryd999** [w3ctag/design-reviews#363] opened 2019-04-06 00:19 UTC
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: Simpler reading methods for Blob interface
  - Explainer, Requirements Doc, or Example code: https://github.com/w3c/FileAPI/pull/117
  - Tests: https://crrev.com/c/1529716
  - Primary contacts: @jarryd999, @mkruisselbrink

Further details (optional):

  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The assessment is not relevant for this feature.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that this is an addition to existing major API that can easily be polyfilled.

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by mkruisselbrink** [comment] 2019-04-06 00:40
Sorry, this is a duplicate of #359

**Closed** 2019-04-06 01:03 UTC
